spring.profiles.active: dev

spring.jpa.show-sql: true

---
#development environment
spring:
  profiles: dev
  # datasource
  datasource:
    url: jdbc:mysql://localhost:3307/gitblog?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  # jpa
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, update)
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false

server:
  port: 8080

---
#test environment
spring:
  profiles: test
  thymeleaf:
    cache: false

server:
  port: 8180

---
#production environment
spring:
  profiles: prod
  thymeleaf:
    cache: false

server:
  port: 8080
