spring.profiles.active: dev

spring.jpa.show-sql: true

---
#development environment
spring:
  profiles: dev
#  datasource:
#    url: jdbc:mysql://localhost:3306/sample?useSSL=false&allowPublicKeyRetrieval=true
#    username: local
#    password: local

server:
  port: 8080

---
#test environment
spring:
  profiles: test

server:
  port: 8180

---
#production environment
spring:
  profiles: prod

server:
  port: 8080
